sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tahauygun/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true tahauygun/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-029696522603"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
