sudo: required
services:
  - docker

before_install:
  - docker build -t tahauygun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tahauygun/react-test npm test

after_success:
  - docker build -t tahauygun/multi-client ./client
  - docker build -t tahauygun/multi-nginx ./nginx
  - docker build -t tahauygun/multi-server ./server
  - docker build -t tahauygun/multi-worker ./worker

  # Login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push tahauygun/multi-client
  - docker push tahauygun/multi-nginx
  - docker push tahauygun/multi-server
  - docker push tahauygun/multi-worker
